//
//  CalendarDesignKit.swift
//  CalendarKit
//
//  Created by Steven Beyers on 6/17/15.
//  Copyright (c) 2015 Beyers Apps, LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class CalendarDesignKit : NSObject {

    //// Cache

    private struct Cache {
        static var foregroundColor: UIColor = UIColor(red: 0.907, green: 0.190, blue: 0.190, alpha: 1.000)
        static var grayCircleColor: UIColor = UIColor(red: 0.682, green: 0.658, blue: 0.658, alpha: 1.000)
        static var dateBackgroundColor: UIColor = UIColor(red: 0.808, green: 0.801, blue: 0.807, alpha: 1.000)
        static var calendarBackgroundColor: UIColor = UIColor(red: 0.094, green: 0.263, blue: 0.431, alpha: 1.000)
    }

    //// Colors

    public class var foregroundColor: UIColor { return Cache.foregroundColor }
    public class var grayCircleColor: UIColor { return Cache.grayCircleColor }
    public class var dateBackgroundColor: UIColor { return Cache.dateBackgroundColor }
    public class var calendarBackgroundColor: UIColor { return Cache.calendarBackgroundColor }

    //// Drawing Methods

    public class func drawSelectedBackground(frame: CGRect) {

        //// DateCircle Drawing
        var dateCirclePath = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 8, frame.minY + 8, frame.width - 16, frame.height - 16))
        CalendarDesignKit.foregroundColor.setFill()
        dateCirclePath.fill()
    }

    public class func drawTodayBackground(frame: CGRect) {

        //// DateCircle Drawing
        var dateCirclePath = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 8, frame.minY + 8, frame.width - 16, frame.height - 16))
        UIColor.redColor().setStroke()
        dateCirclePath.lineWidth = 3
        dateCirclePath.stroke()
    }

    public class func drawDefaultBackground(frame: CGRect) {

        //// DateCircle Drawing
        var dateCirclePath = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 8, frame.minY + 8, frame.width - 16, frame.height - 16))
        CalendarDesignKit.grayCircleColor.setStroke()
        dateCirclePath.lineWidth = 3
        dateCirclePath.stroke()
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
